### ISSUE TITLE
Interpolating around NaNs

### ISSUE THREAD

**Issue by aloleary93** [raacampbell/shadedErrorBar#10]
Hi there,

The script seems to interpolate around NaN values so that the error bar patch forms a continuous area. Is there a way to avoid this? I.e. present NaN values as discontinuous gaps in the shaded error bar? 

Best,

Alice

**Comment by raacampbell** [comment]
Yeah... I know. How are you supplying the data? e.g. do you gave a matrix of some sort which contains the odd NaN then you see them when the function calculates the mean and standard error?

**Comment by cremy33** [comment]
Hello,

I have the same issue as Alice.
Is there a way to avoid the interpolation around NaN values ? 
I use vectors for the x, y and errBar parameters.

Best, Rémy
