### ISSUE TITLE
Error using shadedErrorBar : length(x) must equal length(errBar)

### ISSUE THREAD

**Issue by zuhayousuf** [raacampbell/shadedErrorBar#15]
So I've been trying to use shadedErrorBar for displaying the error bars for three lines of data that I have. I'm having a little difficulty understanding what the error message means (Error using shadedErrorBar : length(x) must equal length(errBar))

If it helps, I'm also gonna provide the sizes of each of these variables:
averaged_time_alfax and averaged_alfax= 19x1779 (I only want to plot the first row of each of these though, as shown in my code)
averaged_time_dex and averaged_dex= 28x1779
averaged_time_propofol and averaged_propofol= 21x1779

I'm attaching a part of my code below where I'm trying to plot my data:

**Matlab Code:**
plot(averaged_time_alfax(1,:),averaged_alfax(1,:),'Color','[0 0.42 0.64]','LineWidth' ,2);
hold on
plot(averaged_time_dex(1,:),averaged_dex(1,:),'Color','[1 0.50 0.05]','LineWidth' ,2);
hold on
plot(averaged_time_prop(1,:),averaged_prop(1,:),'Color','[0.67 0.67 0.67]','LineWidth' ,2);
hold on % Shaded Error Bars
shadedErrorBar(averaged_time_alfax(1,:),averaged_alfax(1,:),{@mean,@std}, 'lineprops', {'color', [0 0.42 0.64]})
hold on
shadedErrorBar(averaged_time_dex(1,:),averaged_dex(1,:),{@mean,@std},'lineprops', {'color', [1 0.50 0.05]})
hold on
shadedErrorBar(averaged_time_prop(1,:),averaged_prop(1,:),{@mean,@std}, 'lineprops', {'color', [0.67 0.67 0.67]})

**Comment by raacampbell** [comment]
The error is cryptic, but the problem is that you're using the wrong input args. Instead do:
```
shadedErrorBar([],averaged_time_alfax,{@mean,@std})
```
The point is that you want to plot the mean and SD of the data. So you want to feed the whole matrix.

**Comment by zuhayousuf** [comment]
But I want to shade the the averaged_alfax rather than the averaged_time_alfax. That's just the time over which the data is plotted. Shouldn't I be putting averaged_alfax in that argument then?

**Comment by raacampbell** [comment]
The second input argument needs to be a matrix.

**Comment by zuhayousuf** [comment]
I converted the variables from vectors to matrices using the vec2mat command, but it's still not working.

**Comment by raacampbell** [comment]
That's not at all what I meant. Please see the examples of how the functions work.
