### ISSUE TITLE
Issues with plotting decimals?

### ISSUE THREAD

**Issue by dlizleblanc** [raacampbell/shadedErrorBar#19]
I'm getting the following error when I try to use the shadedErrorBar function to plot decimals: 

Array indices must be positive integers or logical values.

Error in shadedErrorBar (line 99)
    errBar=fun2(y);

Any idea of how to work around this?

**Comment by raacampbell** [comment]
Can you supply an example code snippet that I can try? Use random data so you don't need to send me your data.

**Comment by dlizleblanc** [comment]
Here's an example: 

x = 1:5;
y = [1e-16, 2e-14, 3e-16, 3e-15, 2e-12];
mean1 = mean(y);
std1 = std(y);

clf
shadedErrorBar(x,y,{mean1,std1}); 

% Overlay the raw data
hold on
plot(x,y,'.','color',[0.5,0.5,0.95])

grid on

**Comment by raacampbell** [comment]
I think you're just calling it incorrectly. Take another look at the examples in `help shadedErrorBar` (some of which I reproduce below).

```
  y=randn(30,80); 
  x=1:size(y,2);
```
Note above how `y` is a *matrix* and `x` is a vector. In your example both were vectors.
 
Now we call the function like this:
```
  shadedErrorBar(x,mean(y,1),std(y),'lineProps','g');
```
Note that the first three inputs are vectors in this case. There is a second call style where the second input (`y`) is a matrix and a cell array of function handles determines how to draw the central line and the error region. They work on `y`.
 
```
  shadedErrorBar(x,y,{@median,@std},'lineProps',{'r-o','markerfacecolor','r'});
``` 

You did something a bit like that but your `y` was a vector. Also note above that `{@median,@std}` is a cell array of *function handles*. You provided a cell array containing two scalars.

**Comment by dlizleblanc** [comment]
That all makes a lot of sense. Thanks for clarifying. 

I'm still however getting the following error: 

```
Error using shadedErrorBar (line 127)
length(x) must equal length(errBar)
```

**Comment by raacampbell** [comment]
Again, I will need an example code snippet. There is no way I can guess what produced an error otherwise.
