### ISSUE TITLE
Change line color from basic matlab colors

### ISSUE THREAD

**Issue by WJRed** [raacampbell/shadedErrorBar#21]
Hi, great work,

is there any way to change the main line color? In all of the examples given, I see examples for the short name basic colors, i.e. 'r', 'b', 'g', etc but nothing about how to change it to custom value using RGB [x, y, z].

Thanks,

William

**Comment by raacampbell** [comment]
The example in the readme shows how to change properties post-hoc, and this would do what you want. You can also do `shadedErrorBar(x, y, err_bar(y) ,'lineprops', {'color', [0.5, 1, 1]});

**Comment by WJRed** [comment]
Thanks for this,

I am using the post-hoc script but was missing the 'color'.

Regards,

William
