### ISSUE TITLE
Can not draw the results to UIFigure. 

### ISSUE THREAD

**Issue by christzhang2022** [raacampbell/shadedErrorBar#23]
I want to draw the figure with shaded error bars in an existing axis area in a "UIFigure“. But it always draw the figure by opening a new figure. However, it won't open a new figure when I designate an axis in a “”Figure”. In other words, the function works fine with "Figure", but not with ”UIFigure”. Could anyone fix it?

**Comment by raacampbell** [comment]
Done - 80c07a5d29ce957f3d65a8f402bbb34a98518611 
See new example. You have to specify the axis.

**Comment by christzhang2022** [comment]
Hi, thank you for your brilliant work and prompt response. The revised function works well. It will plot in the specified axis area. But I don't know why it always pop up an empty figure when I draw the plot in a "uifigure".  My codes are as follows: 

data = [1	0.30	0.22
2	0.40	0.19
3	0.52	0.11
4	0.61	0.15
5	0.39	0.50
6	0.30	0.19
7	0.20	0.22
8	0.09	0.10
9	0.07	0.11
10	0.05	0.18
11	0.05	0.21]; 

x = data(:,1); 
y= data(:,2); 
ysd = data(:,3); 
yErrBar = [ysd ysd]; 

fig = uifigure;  
fig.AutoResizeChildren = 'off';
h0 = subplot(2,1,1,'parent', fig);
h = shadedErrorBar(x, y, yErrBar, 'plotAxes', h0);
