### ISSUE TITLE
Error using strfind() matlab 2021a

### ISSUE THREAD

**Issue by hisunjiang** [raacampbell/shadedErrorBar#24]
Hello,

Thanks for your code.
When I am trying this code, I got this issue:
''
Error using strfind
Search term must be a text or pattern scalar.

Error in contains (line 88)
tf = ~cellfun(@isempty, strfind(s, pattern));

Error in matlab.ui.internal.prepareFigureFor

Error in uistack (line 69)
    matlab.ui.internal.prepareFigureFor(morphFig, mfilename('fullpath'))

Error in shadedErrorBar>makePlot (line 260)
        uistack(H.mainLine,'top')

Error in shadedErrorBar (line 159)
H = makePlot(x,y,errBar,lineProps,transparent,patchSaturation,plotAxes);
''

Do you have any idea what's happening?

Kind regards.

**Comment by raacampbell** [comment]
Please provide an example that can be run by anyone that reproduces this
error.

**Comment by hisunjiang** [comment]
Hello,

I ran your basic example and then got this issue. The only difference is that I installed the Fieldtrip toolbox, which may be incompatible with some Matlab default functions. Here, the problem comes from uistack(H.mainLine,'top'). I commented on Lines 257-266, then it works.

Thanks.

**Comment by raacampbell** [comment]
I can't replicate your issue in R2022b and I don't recall it coming up before. I don't think FieldTrip is of any relevance here: it has no function named `uistack` which could be masking a built-in. If I find machine with R2021a (or any other recent version) I will test again. I would be surprised if this line failed, though. It doesn't make sense. 

Can you try closing and re-start MATLAB then running
```
  y=randn(30,80); 
  x=1:size(y,2);
  shadedErrorBar(x,mean(y,1),std(y),'lineProps','g');
 ```

**Comment by hisunjiang** [comment]
Hello, I got closer to the origin of this problem. When installing FieldTrip (yes, the one for EEG signals), I added all its folders and subfolders to the MATLAB search path, which causes this problem. When I tried to just add folders, then every example you provided worked. The same procedure I tried with R2023a and got the same results.

**Comment by raacampbell** [comment]
Ok, I'll forward this Issue thread to them.
