### ISSUE TITLE
Vector + transparency seems possible

### ISSUE THREAD

**Issue by jebej** [raacampbell/shadedErrorBar#9]
It seems using the painters renderer with an alpha value is able to produce a vector graphic, at least on R2015b (my current version). I tested this by changing the commenting out a few lines:

```matlab
%if transparent
    faceAlpha=patchSaturation;
    patchColor=col;
%    set(gcf,'renderer','openGL')
%else
%    faceAlpha=1;
%    patchColor=col+(1-col)*(1-patchSaturation);
    set(gcf,'renderer','painters')
%end
```
This allowed me to produce the following PDF file: [iv_plot_job_DEBUG_20170804192520.pdf](https://github.com/raacampbell/shadedErrorBar/files/1202404/iv_plot_job_DEBUG_20170804192520.pdf)

**Comment by raacampbell** [comment]
This works for me to on R2017a but only if I export as PDF not if I export as EPS. I guess you were saving as PDF?

**Comment by jebej** [comment]
Yes. It might be a good idea to use painters with transparency by default (as the MATLAB plot window supports it), and warn that vector output will work with PDF, but not EPS. Then there can be a switch to turn off transparency for EPS vector output.

**Comment by jebej** [comment]
Transparency by default is a bit nicer as well because it will not hide the ticks.

**Comment by raacampbell** [comment]
That seems reasonable. See if the latest commit in the dev branch does what you want. It's param/val pairs now for input args after the third.

**Comment by jebej** [comment]
That looks good! Will saving as EPS without manually switching the renderer disable transparency and save a vector image then?

**Comment by raacampbell** [comment]
On my system the default renderer seems to be OpenGL, so I would get a transparent raster image by default if I saved as EPS. I felt it was probably better not to silently change the renderer.

**Comment by raacampbell** [comment]
merged changes into master.
